---
tools:
  ap:
    executable: AnalysisPrograms.exe
    command: "audio2csv {source} {config} {output} --no-debug"
    result_pattern: "*.Events.beta.json"
  # avianz:
  #   executable: "echo.exe"
  #   command: "{source} {config} {output} {tempdir}"
  #   result_pattern: ""

test_suites:
  boobook:
    default_label: NinoxBoobook
    tool_configs:
      ap:
        config: Towsey.NinoxBoobook.yml
      avianz:
        config: boobook.json
    tests:
      - file: ..\..\tests\Fixtures\Powerful3AndBoobook0_ksh3_1773_510819_20171109_174311_30_0.wav
        expect:
          - segment_with: event_count
            count: 3
          - label: NinoxBoobook
            bounds: [7.86±0.1, ">210", 8.98±0.5, "<1050"]
          - label: NinoxBoobook
            bounds: [16.2±0.1, ">210", 17.4±0.5, "<1050"]
          - label: NinoxBoobook
            bounds: [26.8±0.1, ">210", 27.89±0.5, "<1050"]
      - file: ..\..\tests\Fixtures\Powerful3AndBoobook0_ksh3_1773_510819_20171109_174311_30_0.wav
        expect:
          - segment_with: event_count
            count: 4
    #       expect:
    #           - segment_with: no_events
    #       expect_events:
    #           - label: NinoxBoobookk
    #             bounds: [7.86±0.1, ">210", 8.98±0.5, "<1050"]
    #           - label: NinoxBoobook
    #             bounds: [16.2±0.1, ">210", 17.4±0.5, "<1050"]
    #           - label: NinoxBoobook
    #             bounds: [26.8±0.1, ">210", 27.89±0.5, "<1050"]
    #             #- label: boobook
    #             #  bounds: [10, 130, 20, 300]
    #             #- label: boobook
    #             #  centroid: [10, 30]
    #             #  duration: ">1.0"
    #             #  bandwidth: ">1.0"
    #             #- label: powerful_owl
    #             #  match: false
    #             #- condition: 'label.startsWith("boo")'
    # #   - uri: ecosounds.org/123.wav
    #     expect:
    #       # ...
    #include_cases: [geophony]

common_cases:
  geophony:
    - file: windy.wav
      expect:
        - segment_with: event_count
    - file: rainy.wav
      expect:
        - segment_with: event_count
          count: 0
