/* visualize this here: https://bottlecaps.de/rr/ui */
/* or generate docs images with  grammkit -t md  -f ebnf  interval.ebnf   */
 
expression ::= number | tolerance | relation | interval | approximation
tolerance ::= number "±" number
relation ::= (">" | "<" | "≥" | "≤") number
approximation ::= ( "~" | "≈") number
interval ::= ("[" | "(") number "," number (")" | "]")

number ::= constant | real
constant ::= "ε" | "∞" | "-∞"
real ::= pos | neg | zero
pos ::= digit+ ("." digit+ )?
neg ::= "-" pos
digit ::=  [0-9]
